version: 2

build:
  os: "ubuntu-22.04"
  apt_packages:
      - openjdk-21-jdk
      - libsaxon-java
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
      - wget -O /usr/local/bin/saxon-he.jar "https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/12.4/Saxon-HE-12.4.jar"
      - ls -ltr /usr/local/bin/saxon-he.jar
      - if [ -f /usr/local/bin/saxon-he.jar ]; then echo "Saxon-HE jar downloaded successfully"; else echo "Failed to download Saxon-HE jar"; fi
      - export CLASSPATH=$CLASSPATH:/usr/local/bin/saxon-he.jar
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false
